// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/user/authenticator_admin.proto

package userpb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SetAdminFlagRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SetAdminFlagRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetAdminFlagRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SetAdminFlagRequestMultiError, or nil if none found.
func (m *SetAdminFlagRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SetAdminFlagRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetBizId()) < 1 {
		err := SetAdminFlagRequestValidationError{
			field:  "BizId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetUserId()) < 1 {
		err := SetAdminFlagRequestValidationError{
			field:  "UserId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for AdminFlag

	if len(errors) > 0 {
		return SetAdminFlagRequestMultiError(errors)
	}

	return nil
}

// SetAdminFlagRequestMultiError is an error wrapping multiple validation
// errors returned by SetAdminFlagRequest.ValidateAll() if the designated
// constraints aren't met.
type SetAdminFlagRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetAdminFlagRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetAdminFlagRequestMultiError) AllErrors() []error { return m }

// SetAdminFlagRequestValidationError is the validation error returned by
// SetAdminFlagRequest.Validate if the designated constraints aren't met.
type SetAdminFlagRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetAdminFlagRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetAdminFlagRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetAdminFlagRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetAdminFlagRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetAdminFlagRequestValidationError) ErrorName() string {
	return "SetAdminFlagRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SetAdminFlagRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetAdminFlagRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetAdminFlagRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetAdminFlagRequestValidationError{}

// Validate checks the field values on SetAdminFlagResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SetAdminFlagResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetAdminFlagResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SetAdminFlagResponseMultiError, or nil if none found.
func (m *SetAdminFlagResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SetAdminFlagResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetStatus()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SetAdminFlagResponseValidationError{
					field:  "Status",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SetAdminFlagResponseValidationError{
					field:  "Status",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStatus()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SetAdminFlagResponseValidationError{
				field:  "Status",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SetAdminFlagResponseMultiError(errors)
	}

	return nil
}

// SetAdminFlagResponseMultiError is an error wrapping multiple validation
// errors returned by SetAdminFlagResponse.ValidateAll() if the designated
// constraints aren't met.
type SetAdminFlagResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetAdminFlagResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetAdminFlagResponseMultiError) AllErrors() []error { return m }

// SetAdminFlagResponseValidationError is the validation error returned by
// SetAdminFlagResponse.Validate if the designated constraints aren't met.
type SetAdminFlagResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetAdminFlagResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetAdminFlagResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetAdminFlagResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetAdminFlagResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetAdminFlagResponseValidationError) ErrorName() string {
	return "SetAdminFlagResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SetAdminFlagResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetAdminFlagResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetAdminFlagResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetAdminFlagResponseValidationError{}
